// src/infrastructure/sqlite/memoryRepository.ts — SQLite 事务仓储：primary/FTS/vector fencing/outbox 同事务，作用域隔离
import { createHash } from 'node:crypto';
import type { Db } from '../../store/db.js';
import { bigramZh } from './bigramZh.js';
import { gatewayError } from '../../protocol/errors.js';
import { err, ok } from '../../protocol/results.js';
import { accessibleScopes, MEMORY_SCOPE_WEIGHT, resolveWriteScope, type MemoryScope } from '../../domain/memory/memoryScope.js';
import { rankMemoryCandidates } from '../../domain/memory/memoryRanking.js';
import type { IndexHealthIssue, MemoryPatch, MemoryProvenance, MemoryQuery, MemoryRecord, MemoryRepository, RetentionAction } from '../../domain/memory/memoryRepository.js';

const hash = (s: string) => createHash('sha256').update(s.normalize('NFKC')).digest('hex');
const clamp = (n: number) => Math.max(0, Math.min(1, n));

export function openMemoryRepository(db: Db, options: { now(): number; idFactory(prefix: string): string }): MemoryRepository & { getActive(id: string): MemoryRecord | null } {
  const record = (r: Record<string, unknown>): MemoryRecord => ({ id: String(r.id), scopeTier: r.scope_tier as MemoryRecord['scopeTier'], scopeKey: String(r.scope_key), role: r.role as MemoryRecord['role'], content: String(r.content), contentHash: String(r.content_hash), generation: Number(r.generation), embeddingState: r.embedding_state as MemoryRecord['embeddingState'], salience: Number(r.salience), provenance: JSON.parse(String(r.provenance_json)), sourceTrust: Number(r.source_trust), retention: { class: r.retention_class as MemoryRecord['retention']['class'], retainUntil: r.retain_until === null ? null : new Date(Number(r.retain_until)).toISOString() }, createdAt: new Date(Number(r.created_at)).toISOString(), updatedAt: new Date(Number(r.updated_at)).toISOString(), lastSeenAt: new Date(Number(r.last_seen_at)).toISOString(), dedupCount: Number(r.dedup_count), tombstonedAt: r.tombstoned_at === null ? null : new Date(Number(r.tombstoned_at)).toISOString() });
  const filter = (scope: MemoryScope) => {
    const scopes = accessibleScopes(scope); if (!scopes.length) return null;
    return { sql: scopes.map((_, i) => `(r.scope_tier=@t${i} AND r.scope_key=@k${i})`).join(' OR '), params: Object.fromEntries(scopes.flatMap((s, i) => [[`t${i}`, s.tier], [`k${i}`, s.key]])) };
  };
  const owned = (id: string, scope: MemoryScope) => { const f = filter(scope); if (!f) return err(gatewayError('MEMORY_SCOPE_REQUIRED', 'scope 必填', 'memory.scope.required')); const row = db.prepare(`SELECT * FROM memory_records r WHERE r.id=@id AND r.tombstoned_at IS NULL AND (${f.sql})`).get({ id, ...f.params }) as Record<string, unknown> | undefined; return row ? ok(row) : err(gatewayError('MEMORY_SCOPE_DENIED', 'memory scope 拒绝', 'memory.scope.denied')); };
  const tombstone = db.transaction((id: string, now: number) => { db.prepare(`UPDATE memory_records SET embedding_state='tombstoned',tombstoned_at=?,updated_at=? WHERE id=? AND tombstoned_at IS NULL`).run(now, now, id); db.prepare(`DELETE FROM memory_fts WHERE record_id=?`).run(id); db.prepare(`DELETE FROM memory_vectors WHERE record_id=?`).run(id); db.prepare(`UPDATE embedding_jobs SET state='tombstoned',lease_owner=NULL,lease_until=NULL,updated_at=? WHERE record_id=? AND state!='ready'`).run(now, id); });
  const api: MemoryRepository & { getActive(id: string): MemoryRecord | null } = {
    append(input, scope) {
      try { return db.transaction(() => {
        const target = resolveWriteScope(scope); if (!target.ok) return target; const now = options.now(); const content = input.content.normalize('NFKC'); const contentHash = hash(content);
        const existing = db.prepare(`SELECT * FROM memory_records WHERE scope_tier=? AND scope_key=? AND role=? AND content_hash=? AND tombstoned_at IS NULL`).get(target.value.tier, target.value.key, input.role, contentHash) as Record<string, unknown> | undefined;
        const provenance: MemoryProvenance = { ...input.provenance, sourceTrust: clamp(input.provenance.sourceTrust), contentHash };
        if (existing) { const list = JSON.parse(String(existing.provenance_json)) as MemoryProvenance[]; if (!list.some(p => p.sourceType === provenance.sourceType && p.sourceId === provenance.sourceId && p.contentHash === contentHash)) list.push(provenance); db.prepare(`UPDATE memory_records SET provenance_json=?,source_trust=?,last_seen_at=?,updated_at=?,dedup_count=dedup_count+1 WHERE id=?`).run(JSON.stringify(list), Math.max(Number(existing.source_trust), provenance.sourceTrust), now, now, existing.id); return ok({ record: record(db.prepare(`SELECT * FROM memory_records WHERE id=?`).get(existing.id) as Record<string, unknown>), deduplicated: true }); }
        const id = options.idFactory('memory'); const retainUntil = input.retention.retainUntil === null ? null : Date.parse(input.retention.retainUntil);
        db.prepare(`INSERT INTO memory_records VALUES (?,?,?,?,?,?,1,'pending',?,?,?,?,?,?,?,?,1,NULL)`).run(id, target.value.tier, target.value.key, input.role, content, contentHash, clamp(input.salience), JSON.stringify([provenance]), provenance.sourceTrust, input.retention.class, retainUntil, now, now, now);
        db.prepare(`INSERT INTO memory_fts VALUES (?,?,?,?)`).run(id, target.value.tier, target.value.key, bigramZh(content));
        db.prepare(`INSERT INTO embedding_jobs(id,record_id,generation,state,attempts,available_at,created_at,updated_at) VALUES (?,?,1,'pending',0,?,?,?)`).run(options.idFactory('embedding-job'), id, now, now, now);
        return ok({ record: record(db.prepare(`SELECT * FROM memory_records WHERE id=?`).get(id) as Record<string, unknown>), deduplicated: false });
      })(); } catch (cause) { return err(gatewayError('MEMORY_TRANSACTION_FAILED', 'memory append transaction 失败', 'memory.transaction.failed', { retryable: false, details: { cause: String(cause) } })); }
    },
    update(id, patch: MemoryPatch, scope) {
      try { return db.transaction(() => { const current = owned(id, scope); if (!current.ok) return current; const before = record(current.value); const now = options.now(); const content = (patch.content ?? before.content).normalize('NFKC'); const generation = before.generation + 1; const list = [...before.provenance]; if (patch.provenance) list.push({ ...patch.provenance, sourceTrust: clamp(patch.provenance.sourceTrust), contentHash: hash(content) }); const retention = patch.retention ?? before.retention; db.prepare(`UPDATE memory_records SET content=?,content_hash=?,generation=?,embedding_state='pending',salience=?,provenance_json=?,source_trust=?,retention_class=?,retain_until=?,updated_at=? WHERE id=?`).run(content, hash(content), generation, clamp(patch.salience ?? before.salience), JSON.stringify(list), Math.max(...list.map(p => p.sourceTrust)), retention.class, retention.retainUntil === null ? null : Date.parse(retention.retainUntil), now, id); db.prepare(`DELETE FROM memory_fts WHERE record_id=?`).run(id); db.prepare(`INSERT INTO memory_fts VALUES (?,?,?,?)`).run(id, before.scopeTier, before.scopeKey, bigramZh(content)); db.prepare(`DELETE FROM memory_vectors WHERE record_id=?`).run(id); db.prepare(`UPDATE embedding_jobs SET state='tombstoned',updated_at=? WHERE record_id=? AND generation<?`).run(now, id, generation); db.prepare(`INSERT INTO embedding_jobs(id,record_id,generation,state,attempts,available_at,created_at,updated_at) VALUES (?,?,?,'pending',0,?,?,?)`).run(options.idFactory('embedding-job'), id, generation, now, now, now); return ok(record(db.prepare(`SELECT * FROM memory_records WHERE id=?`).get(id) as Record<string, unknown>)); })(); } catch (cause) { return err(gatewayError('MEMORY_TRANSACTION_FAILED', 'memory update transaction 失败', 'memory.transaction.failed', { retryable: false, details: { cause: String(cause) } })); }
    },
    delete(id, scope) { const check = owned(id, scope); if (!check.ok) return check; try { tombstone(id, options.now()); return ok(undefined); } catch (cause) { return err(gatewayError('MEMORY_TRANSACTION_FAILED', 'memory delete transaction 失败', 'memory.transaction.failed', { retryable: false, details: { cause: String(cause) } })); } },
    search(query: MemoryQuery, scope) {
      const f = filter(scope); if (!f) return err(gatewayError('MEMORY_SCOPE_REQUIRED', 'scope 必填', 'memory.scope.required'));
      const rows = db.prepare(`SELECT r.*,bm25(memory_fts) fts_rank,v.embedding_json FROM memory_fts JOIN memory_records r ON r.id=memory_fts.record_id LEFT JOIN memory_vectors v ON v.record_id=r.id AND v.generation=r.generation WHERE memory_fts MATCH @match AND r.tombstoned_at IS NULL AND (${f.sql}) LIMIT @limit`).all({ match: bigramZh(query.text), limit: Math.max(query.limit * 8, 32), ...f.params }) as Array<Record<string, unknown>>;
      const ranked = rankMemoryCandidates(rows.map(r => ({ id: String(r.id), fts: 1 / (1 + Math.abs(Number(r.fts_rank))), vector: 0, recency: 1 / (1 + Math.max(0, Date.parse(query.now) - Number(r.updated_at)) / (30 * 86_400_000)), salience: Number(r.salience), sourceTrust: Number(r.source_trust), scopeWeight: MEMORY_SCOPE_WEIGHT[r.scope_tier as keyof typeof MEMORY_SCOPE_WEIGHT] })));
      const byId = new Map(rows.map(r => [String(r.id), r])); return ok(ranked.slice(0, query.limit).map(x => ({ record: record(byId.get(x.id)!), score: x.score, components: x.components })));
    },
    list(scope, options) {
      const f = filter(scope); if (!f) return err(gatewayError('MEMORY_SCOPE_REQUIRED', 'scope 必填', 'memory.scope.required'));
      try {
        const rows = db.prepare(`SELECT * FROM memory_records r WHERE r.tombstoned_at IS NULL AND (${f.sql}) ORDER BY r.updated_at DESC LIMIT @limit`)
          .all({ limit: Math.min(Math.max(options.limit, 1), 100), ...f.params }) as Array<Record<string, unknown>>;
        return ok(rows.map(record));
      } catch (cause) { return err(gatewayError('MEMORY_TRANSACTION_FAILED', 'memory list 失败', 'memory.transaction.failed', { retryable: false, details: { cause: String(cause) } })); }
    },
    rebuild(scope) { const f = filter(scope); if (!f) return err(gatewayError('MEMORY_SCOPE_REQUIRED', 'scope 必填', 'memory.scope.required')); try { const report = db.transaction(() => { const before = db.prepare(`SELECT COUNT(*) c FROM memory_vectors WHERE record_id NOT IN (SELECT id FROM memory_records WHERE tombstoned_at IS NULL)`).get() as { c: number }; db.prepare(`DELETE FROM memory_vectors WHERE record_id NOT IN (SELECT id FROM memory_records WHERE tombstoned_at IS NULL)`).run(); const rows = db.prepare(`SELECT * FROM memory_records r WHERE r.tombstoned_at IS NULL AND (${f.sql}) ORDER BY r.id`).all(f.params) as Array<Record<string, unknown>>; for (const r of rows) { db.prepare(`DELETE FROM memory_fts WHERE record_id=?`).run(r.id); db.prepare(`INSERT INTO memory_fts VALUES (?,?,?,?)`).run(r.id, r.scope_tier, r.scope_key, bigramZh(String(r.content))); if (r.embedding_state !== 'ready') db.prepare(`INSERT OR IGNORE INTO embedding_jobs(id,record_id,generation,state,attempts,available_at,created_at,updated_at) VALUES (?,?,?,'pending',0,?,?,?)`).run(`rebuild:${r.id}:${r.generation}`, r.id, r.generation, options.now(), options.now(), options.now()); } return { activeRecords: rows.length, ftsRows: rows.length, queuedEmbeddings: rows.filter(r => r.embedding_state !== 'ready').length, removedOrphans: before.c }; })(); return ok(report); } catch (cause) { return err(gatewayError('MEMORY_TRANSACTION_FAILED', 'memory rebuild transaction 失败', 'memory.transaction.failed', { retryable: false, details: { cause: String(cause) } })); } },
    inspectIndexHealth(now, maxStale) { const issues: IndexHealthIssue[] = []; issues.push(...(db.prepare(`SELECT record_id,created_at FROM embedding_jobs WHERE state IN ('pending','processing') AND created_at<=?`).all(now - maxStale) as Array<{ record_id: string; created_at: number }>).map(r => ({ code: 'EMBEDDING_MAX_STALE_EXCEEDED' as const, recordId: r.record_id, ageMs: now - r.created_at }))); issues.push(...(db.prepare(`SELECT v.record_id FROM memory_vectors v LEFT JOIN memory_records r ON r.id=v.record_id WHERE r.id IS NULL OR r.tombstoned_at IS NOT NULL OR r.generation!=v.generation`).all() as Array<{ record_id: string }>).map(r => ({ code: 'EMBEDDING_ORPHAN_VECTOR' as const, recordId: r.record_id }))); issues.push(...(db.prepare(`SELECT r.id FROM memory_records r LEFT JOIN memory_vectors v ON v.record_id=r.id AND v.generation=r.generation WHERE r.tombstoned_at IS NULL AND r.embedding_state='ready' AND v.record_id IS NULL`).all() as Array<{ id: string }>).map(r => ({ code: 'EMBEDDING_VECTOR_MISSING' as const, recordId: r.id }))); return issues; },
    retentionPlan(now) { return (db.prepare(`SELECT id,retain_until FROM memory_records WHERE tombstoned_at IS NULL AND retain_until IS NOT NULL AND retain_until<=? ORDER BY retain_until,id`).all(now) as Array<{ id: string; retain_until: number }>).map(r => ({ recordId: r.id, action: 'tombstone', retainUntil: new Date(r.retain_until).toISOString() })); },
    applyRetention(actions: readonly RetentionAction[], now) { try { db.transaction(() => { for (const action of actions) tombstone(action.recordId, now); })(); return ok(actions.length); } catch (cause) { return err(gatewayError('MEMORY_TRANSACTION_FAILED', 'retention transaction 失败', 'memory.transaction.failed', { retryable: false, details: { cause: String(cause) } })); } },
    getActive(id) { const row = db.prepare(`SELECT * FROM memory_records WHERE id=? AND tombstoned_at IS NULL`).get(id) as Record<string, unknown> | undefined; return row ? record(row) : null; },
  };
  return api;
}
