# wxnodus sandbox runner v3 (generated by kernel/winSandbox.ts)
param([string]$Mode="",[string]$Profile="",[string]$Exe="",[string]$ArgsJson="[]",[string]$Cwd="",[string]$OutPath="",[string]$ErrPath="",[string]$StdinPath="")
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
$ErrorActionPreference = "Stop"
$src = @'
using System;
using System.ComponentModel;
using System.IO;
using System.Runtime.InteropServices;
using System.Text;
public static class WxSandbox {
  [StructLayout(LayoutKind.Sequential)] struct SA { public int nLength; public IntPtr lpSecurityDescriptor; public bool bInheritHandle; }
  [StructLayout(LayoutKind.Sequential)] struct PI { public IntPtr hProcess; public IntPtr hThread; public int dwProcessId; public int dwThreadId; }
  [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)] struct SI { public int cb; public string lpReserved; public string lpDesktop; public string lpTitle; public int dwX; public int dwY; public int dwXSize; public int dwYSize; public int dwXCountChars; public int dwYCountChars; public int dwFillAttribute; public int dwFlags; public short wShowWindow; public short cbReserved2; public IntPtr lpReserved2; public IntPtr hStdInput; public IntPtr hStdOutput; public IntPtr hStdError; }
  [StructLayout(LayoutKind.Sequential)] struct IOC { public ulong a; public ulong b; public ulong c; public ulong d; public ulong e; public ulong f; }
  [StructLayout(LayoutKind.Sequential)] struct JBLI { public long t1; public long t2; public uint flags; public UIntPtr ws1; public UIntPtr ws2; public uint active; public UIntPtr aff; public uint prio; public uint sched; }
  [StructLayout(LayoutKind.Sequential)] struct JELI { public JBLI basic; public IOC io; public UIntPtr pml; public UIntPtr jml; public UIntPtr ppm; public UIntPtr pjm; }
  [StructLayout(LayoutKind.Sequential)] struct JNRC { public ulong MaxBandwidth; public uint ControlFlags; public uint DSCPTag; }
  [StructLayout(LayoutKind.Sequential)] struct SIDATTR { public IntPtr Sid; public uint Attributes; }
  const uint TAP = 0x1, TDUP = 0x2, TQ = 0x8, TAD = 0x80;
  const uint CSUS = 0x4, CUE = 0x400;
  const int USESTDHANDLES = 0x100;
  const int KILLONCLOSE = 0x2000, DIEONEXC = 0x400;
  const uint NRCENABLE = 0x1, NRCMAXBW = 0x4;
  const int JELI_CLASS = 9, NRC_CLASS = 32, TIL_CLASS = 25;
  const uint GENREAD = 0x80000000, GENWRITE = 0x40000000, SHARERW = 3, CREATEALWAYS = 2, FILENORMAL = 0x80;
  const uint INF = 0xFFFFFFFF;
  [DllImport("advapi32.dll", SetLastError = true)] static extern bool OpenProcessToken(IntPtr h, uint access, out IntPtr t);
  [DllImport("advapi32.dll", SetLastError = true)] static extern bool DuplicateTokenEx(IntPtr e, uint access, ref SA sa, int level, int type, out IntPtr nt);
  [DllImport("advapi32.dll", SetLastError = true)] static extern bool ConvertStringSidToSid(string s, out IntPtr sid);
  [DllImport("advapi32.dll", SetLastError = true)] static extern bool SetTokenInformation(IntPtr t, int cls, IntPtr info, uint len);
  [DllImport("kernel32.dll", CharSet = CharSet.Unicode, SetLastError = true)] static extern IntPtr CreateJobObject(IntPtr sa, string name);
  [DllImport("kernel32.dll", SetLastError = true)] static extern bool SetInformationJobObject(IntPtr j, uint cls, IntPtr info, uint len);
  [DllImport("kernel32.dll", SetLastError = true)] static extern bool AssignProcessToJobObject(IntPtr j, IntPtr p);
  [DllImport("kernel32.dll", CharSet = CharSet.Unicode, SetLastError = true)] static extern bool CreateProcessAsUser(IntPtr t, string app, string cmd, IntPtr pa, IntPtr ta, bool inh, uint flags, IntPtr env, string cwd, ref SI si, out PI pi);
  [DllImport("kernel32.dll", CharSet = CharSet.Unicode, SetLastError = true)] static extern bool CreateProcess(string app, string cmd, IntPtr pa, IntPtr ta, bool inh, uint flags, IntPtr env, string cwd, ref SI si, out PI pi);
  [DllImport("kernel32.dll", SetLastError = true)] static extern uint ResumeThread(IntPtr th);
  [DllImport("kernel32.dll", SetLastError = true)] static extern uint WaitForSingleObject(IntPtr h, uint ms);
  [DllImport("kernel32.dll", SetLastError = true)] static extern bool GetExitCodeProcess(IntPtr h, out uint code);
  [DllImport("kernel32.dll", SetLastError = true)] static extern bool CloseHandle(IntPtr h);
  [DllImport("kernel32.dll", CharSet = CharSet.Unicode, SetLastError = true)] static extern IntPtr CreateFile(string name, uint access, uint share, ref SA sa, uint mode, uint flags, IntPtr tmpl);
  // supremacy 3.2 dual-mode sandbox: elevated -> restricted token (disable Administrators + LocalSystem,
  // Medium integrity); standard user -> Low IL (verified). CreateRestrictedToken needs SeTcbPrivilege
  // which standard users lack (1314) - hence the dual path.
  [DllImport("advapi32.dll", SetLastError = true)] static extern bool CreateRestrictedToken(IntPtr e, uint flags, uint dsc, IntPtr sda, uint dpc, IntPtr pda, uint rsc, IntPtr sra, out IntPtr nt);
  [DllImport("advapi32.dll", SetLastError = true)] static extern bool GetTokenInformation(IntPtr t, int cls, IntPtr info, uint len, out uint rlen);
  [DllImport("kernel32.dll", SetLastError = true)] static extern IntPtr LocalFree(IntPtr m);
  const uint DMP = 0x1; // DISABLE_MAX_PRIVILEGE
  const int TELEV_CLASS = 20; // TokenElevation
  const string ADMIN_SID = "S-1-5-32-544"; // BUILTIN\Administrators
  const string SYSTEM_SID = "S-1-5-18"; // LocalSystem
  const string MEDIUM_IL_SID = "S-1-16-8192"; // SECURITY_MANDATORY_MEDIUM_RID
  // stdout/stderr/stdin redirect file handles MUST be inheritable (CreateProcess bInheritHandles):
  // CreateFile with lpSecurityAttributes=NULL yields non-inheritable handles, child std handles
  // become invalid and all output is silently lost. Keep this embedded C# block ASCII-only:
  // Add-Type -TypeDefinition corrupts non-ASCII on non-UTF8 system code pages (verified:
  // Chinese comments broke parsing - runner regenerated with ASCII-only block).
  static IntPtr InheritFile(string path, uint access, uint mode) {
    SA sa = new SA();
    sa.nLength = Marshal.SizeOf(typeof(SA));
    sa.bInheritHandle = true;
    return CreateFile(path, access, SHARERW, ref sa, mode, FILENORMAL, IntPtr.Zero);
  }
  static string Err() { return new Win32Exception().Message + " (" + new Win32Exception().NativeErrorCode + ")"; }
  // Low IL: S-1-16-4096 (SECURITY_MANDATORY_LOW_RID) as TokenIntegrityLevel.
  // Verified on standard user: SetTokenInformation works without TCB; Low IL child gets
  // ACCESS_DENIED writing Medium-IL files - that is the L0 read-only semantics.
  static void SetLowIL(IntPtr token) {
    IntPtr sid;
    if (!ConvertStringSidToSid("S-1-16-4096", out sid)) throw new Exception("LowIL-SID:" + Err());
    SIDATTR tml = new SIDATTR();
    tml.Sid = sid;
    tml.Attributes = 0x20 | 0x40; // SE_GROUP_INTEGRITY | SE_GROUP_INTEGRITY_ENABLED
    int tsize = Marshal.SizeOf(typeof(SIDATTR));
    IntPtr tbuf = Marshal.AllocHGlobal(tsize);
    Marshal.StructureToPtr(tml, tbuf, false);
    bool ok = SetTokenInformation(token, TIL_CLASS, tbuf, (uint)tsize);
    Marshal.FreeHGlobal(tbuf);
    if (!ok) throw new Exception("SetTokenInformation(LowIL):" + Err());
  }
  // Medium IL on a restricted token: drops the elevated high-integrity marker (defense in depth).
  static void SetMediumIL(IntPtr token) {
    IntPtr sid;
    if (!ConvertStringSidToSid(MEDIUM_IL_SID, out sid)) throw new Exception("MediumIL-SID:" + Err());
    SIDATTR tml = new SIDATTR();
    tml.Sid = sid;
    tml.Attributes = 0x20 | 0x40;
    int tsize = Marshal.SizeOf(typeof(SIDATTR));
    IntPtr tbuf = Marshal.AllocHGlobal(tsize);
    Marshal.StructureToPtr(tml, tbuf, false);
    bool ok = SetTokenInformation(token, TIL_CLASS, tbuf, (uint)tsize);
    Marshal.FreeHGlobal(tbuf);
    if (!ok) throw new Exception("SetTokenInformation(MediumIL):" + Err());
  }
  // Elevated? (TokenElevation) - decides the dual-mode path at runtime.
  static bool IsElevated() {
    IntPtr cur;
    if (!OpenProcessToken(System.Diagnostics.Process.GetCurrentProcess().Handle, TQ, out cur)) return false;
    int size = Marshal.SizeOf(typeof(uint));
    IntPtr buf = Marshal.AllocHGlobal(size);
    uint rlen;
    bool ok = GetTokenInformation(cur, TELEV_CLASS, buf, (uint)size, out rlen);
    uint elevated = ok ? (uint)Marshal.ReadInt32(buf) : 0;
    Marshal.FreeHGlobal(buf);
    CloseHandle(cur);
    return elevated != 0;
  }
  // Restricted token: DISABLE_MAX_PRIVILEGE + disable Administrators/LocalSystem + Medium IL.
  static IntPtr BuildRestrictedToken(IntPtr existing) {
    IntPtr adm; IntPtr sys;
    if (!ConvertStringSidToSid(ADMIN_SID, out adm)) throw new Exception("AdminSID:" + Err());
    if (!ConvertStringSidToSid(SYSTEM_SID, out sys)) throw new Exception("SysSID:" + Err());
    IntPtr[] sids = new IntPtr[] { adm, sys };
    int n = sids.Length;
    IntPtr buf = Marshal.AllocHGlobal(n * IntPtr.Size);
    for (int i = 0; i < n; i++) Marshal.WriteIntPtr(buf, i * IntPtr.Size, sids[i]);
    IntPtr rest;
    bool ok = CreateRestrictedToken(existing, DMP, 0, IntPtr.Zero, 0, IntPtr.Zero, (uint)n, buf, out rest);
    Marshal.FreeHGlobal(buf);
    LocalFree(adm); LocalFree(sys);
    if (!ok) throw new Exception("CreateRestrictedToken:" + Err());
    SetMediumIL(rest);
    return rest;
  }
  public static string Probe() {
    try {
      IntPtr cur;
      if (!OpenProcessToken(System.Diagnostics.Process.GetCurrentProcess().Handle, TDUP | TQ | TAP, out cur)) return "ERR:OpenProcessToken:" + Err();
      SA sa = new SA();
      IntPtr prim;
      if (!DuplicateTokenEx(cur, TAP | TQ | TDUP | TAD, ref sa, 2, 1, out prim)) return "ERR:DuplicateTokenEx:" + Err();
      // Dual mode: elevated -> restricted token is the verifiable capability; standard -> Low IL.
      if (IsElevated()) {
        IntPtr rest = BuildRestrictedToken(prim);
        CloseHandle(rest); CloseHandle(prim); CloseHandle(cur);
        return "OK-ELEVATED";
      }
      SetLowIL(prim);
      IntPtr job = CreateJobObject(IntPtr.Zero, null);
      if (job == IntPtr.Zero) return "ERR:CreateJobObject:" + Err();
      CloseHandle(job); CloseHandle(prim); CloseHandle(cur);
      return "OK-STANDARD";
    } catch (Exception ex) { return "ERR:EX:" + ex.Message; }
  }
  // Minimal JSON string-array parser (escape subset of JSON.stringify: quote, backslash, n, r, t, uXXXX).
  // Not JavaScriptSerializer: .NET Core (pwsh7) lacks System.Web.Extensions; probe degrades honestly.
  static string[] ParseJsonStringArray(string json) {
    var list = new System.Collections.Generic.List<string>();
    int i = 0; int n = json.Length;
    while (i < n && json[i] != (char)91) i++;
    i++;
    while (i < n) {
      while (i < n && (json[i] == (char)32 || json[i] == (char)44 || json[i] == (char)13 || json[i] == (char)10 || json[i] == (char)9)) i++;
      if (i >= n || json[i] == (char)93) break;
      if (json[i] != (char)34) throw new Exception("args-json-bad");
      i++;
      var sb = new StringBuilder();
      while (i < n && json[i] != (char)34) {
        char c = json[i];
        if (c == (char)92 && i + 1 < n) {
          char e = json[i + 1];
          if (e == (char)34) { sb.Append((char)34); i += 2; continue; }
          if (e == (char)92) { sb.Append((char)92); i += 2; continue; }
          if (e == (char)110) { sb.Append((char)10); i += 2; continue; }
          if (e == (char)114) { sb.Append((char)13); i += 2; continue; }
          if (e == (char)116) { sb.Append((char)9); i += 2; continue; }
          if (e == (char)117 && i + 5 < n) { sb.Append((char)Convert.ToInt32(json.Substring(i + 2, 4), 16)); i += 6; continue; }
        }
        sb.Append(c); i++;
      }
      i++;
      list.Add(sb.ToString());
    }
    return list.ToArray();
  }
  // Windows command-line quoting: wrap in quotes, double embedded quotes.
  static string Quote(string s) { return "\"" + s.Replace("\"", "\"\"") + "\""; }
  public static int Run(string profile, string exe, string argsJson, string cwd, string outPath, string errPath, string stdinPath) {
    IntPtr cur;
    if (!OpenProcessToken(System.Diagnostics.Process.GetCurrentProcess().Handle, TDUP | TQ | TAP, out cur)) throw new Exception("OpenProcessToken:" + Err());
    SA sa = new SA();
    IntPtr prim = IntPtr.Zero;
    bool useToken = profile == "L0";
    // supremacy 3.2 dual mode: elevated -> restricted token for L0/L1 (L0 + Low IL for read-only);
    // standard user -> L0 Low IL only (verified on this machine).
    bool elevated = IsElevated();
    bool restricted = elevated && (profile == "L0" || profile == "L1");
    if (restricted || useToken) {
      if (!DuplicateTokenEx(cur, TAP | TQ | TDUP | TAD, ref sa, 2, 1, out prim)) throw new Exception("DuplicateTokenEx:" + Err());
    }
    if (restricted) {
      IntPtr rest = BuildRestrictedToken(prim);
      CloseHandle(prim);
      prim = rest;
      if (profile == "L0") SetLowIL(prim);
    } else if (useToken) {
      SetLowIL(prim);
    }
    IntPtr job = CreateJobObject(IntPtr.Zero, null);
    if (job == IntPtr.Zero) throw new Exception("CreateJobObject:" + Err());
    JELI jel = new JELI();
    jel.basic.flags = (uint)(KILLONCLOSE | DIEONEXC);
    int jsize = Marshal.SizeOf(typeof(JELI));
    IntPtr jbuf = Marshal.AllocHGlobal(jsize);
    Marshal.StructureToPtr(jel, jbuf, false);
    if (!SetInformationJobObject(job, JELI_CLASS, jbuf, (uint)jsize)) throw new Exception("SetInformationJobObject(JELI):" + Err());
    Marshal.FreeHGlobal(jbuf);
    if (profile == "L0" || profile == "L1" || profile == "L2") {
      JNRC nrc = new JNRC();
      nrc.MaxBandwidth = profile == "L2" ? 10240UL : 1UL;
      nrc.ControlFlags = NRCENABLE | NRCMAXBW;
      int nsize = Marshal.SizeOf(typeof(JNRC));
      IntPtr nbuf = Marshal.AllocHGlobal(nsize);
      Marshal.StructureToPtr(nrc, nbuf, false);
      if (!SetInformationJobObject(job, NRC_CLASS, nbuf, (uint)nsize)) throw new Exception("SetInformationJobObject(NRC):" + Err());
      Marshal.FreeHGlobal(nbuf);
    }
    IntPtr hOut = InheritFile(outPath, GENWRITE, CREATEALWAYS);
    IntPtr hErr = InheritFile(errPath, GENWRITE, CREATEALWAYS);
    IntPtr hIn = InheritFile(stdinPath.Length > 0 ? stdinPath : "NUL", GENREAD, 3);
    if (hOut == new IntPtr(-1) || hErr == new IntPtr(-1) || hIn == new IntPtr(-1)) throw new Exception("CreateFile:" + Err());
    SI si = new SI();
    si.cb = Marshal.SizeOf(typeof(SI));
    si.dwFlags = USESTDHANDLES;
    si.hStdOutput = hOut; si.hStdError = hErr; si.hStdInput = hIn;
    var args = ParseJsonStringArray(argsJson);
    var cmdline = new StringBuilder();
    cmdline.Append(Quote(exe));
    foreach (var a in args) { cmdline.Append(" "); cmdline.Append(Quote(a)); }
    PI pi;
    bool ok = (restricted || useToken)
      ? CreateProcessAsUser(prim, null, cmdline.ToString(), IntPtr.Zero, IntPtr.Zero, true, CSUS | CUE, IntPtr.Zero, cwd.Length > 0 ? cwd : null, ref si, out pi)
      : CreateProcess(null, cmdline.ToString(), IntPtr.Zero, IntPtr.Zero, true, CSUS | CUE, IntPtr.Zero, cwd.Length > 0 ? cwd : null, ref si, out pi);
    if (!ok) throw new Exception("CreateProcess:" + Err());
    if (!AssignProcessToJobObject(job, pi.hProcess)) throw new Exception("AssignProcessToJobObject:" + Err());
    ResumeThread(pi.hThread);
    CloseHandle(pi.hThread);
    WaitForSingleObject(pi.hProcess, INF);
    uint code;
    if (!GetExitCodeProcess(pi.hProcess, out code)) throw new Exception("GetExitCodeProcess:" + Err());
    CloseHandle(pi.hProcess); CloseHandle(job);
    if (restricted || useToken) CloseHandle(prim);
    CloseHandle(cur);
    return (int)code;
  }
}
'@
Add-Type -TypeDefinition $src
if ($Mode -eq "probe") { Write-Output ("WX_SANDBOX_PROBE:" + [WxSandbox]::Probe()); exit 0 }
try {
  $code = [WxSandbox]::Run($Profile, $Exe, $ArgsJson, $Cwd, $OutPath, $ErrPath, $StdinPath)
  Write-Output ("WX_SANDBOX_EXIT:" + $code)
  exit 0
} catch {
  Write-Output ("WX_SANDBOX_ERROR:" + $_.Exception.Message)
  exit 127
}