// src/application/release/installerPackager.ts — 完整安装器打包器（§10-4 完整集成）：
// 文件树 → manifest（全量 sha256 绑定）→ 生成 install.ps1（安装前全量校验，漂移即拒）→ 自研 zip 打包（确定性）
// 产物：<appName>-<version>.zip（manifest.json + install.ps1 + 业务文件）——单文件可分发、可校验、可安装
import { createHash } from 'node:crypto';
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { OperationResult } from '../../protocol/results.js';
import { configError } from '../../domain/config/configSchema.js';
import { sanitizeAppName } from './installerManifest.js';
import { buildZip, readZip, zipSha256, type ZipEntryInput } from './zipArchive.js';
import { psSingleQuotedLiteral } from './powershellLiteral.js';
import { validateInstallerPaths } from './installerPathPolicy.js';

export interface InstallerPackageInput {
  appName: string;
  version: string;
  icon: string | null;
  entryPath: string;
  /** 相对路径 → 内容（含入口文件） */
  files: Map<string, Buffer>;
  outDir: string;
}

export interface InstallerPackageResult {
  zipPath: string;
  zipSha256: string;
  manifestSha256: string;
  entryCount: number;
  manifest: InstallerPackageManifest;
}

export interface InstallerPackageManifest {
  schemaVersion: 2;
  appName: string;
  version: string;
  icon: string | null;
  entryPath: string;
  entrySha256: string;
  files: Array<{ path: string; sha256: string; bytes: number }>;
}

const SEMVER = /^\d+\.\d+\.\d+$/;

const sha256 = (bytes: Buffer) => createHash('sha256').update(bytes).digest('hex');

/** install.ps1 模板（纯 ASCII——PS 5.1 无 BOM 时按 ANSI 解析，非 ASCII 注释会损坏解析；写入时加 UTF-8 BOM 双保险）：
 * 安装前对 manifest 全量哈希校验——任何漂移 → INSTALLER_SHA256_MISMATCH / exit 1。
 * P0-03：appName 经 psSingleQuotedLiteral 编码为被动字面量，绝不裸插入 PowerShell 源码。 */
const installScript = (manifest: InstallerPackageManifest): Buffer => {
  const appNameLiteral = psSingleQuotedLiteral(manifest.appName);
  const body = `# wxnodus installer (generated by installerPackager - deterministic install script)
# Verifies every manifest file sha256 before installing; any drift -> exit 1
# DX-04 lifecycle: staging -> postcondition -> atomic switch (backup/rollback recover)
# -> ownership journal (.wxnodus-journal.json); -Uninstall deletes journaled files only.
param(
  [string]$TargetDir = (Join-Path "$env:LOCALAPPDATA\\Programs" ${appNameLiteral}),
  [switch]$DryRun,
  [switch]$Uninstall
)
$ErrorActionPreference = 'Stop'
$Root = Split-Path -Parent $MyInvocation.MyCommand.Path
$ManifestPath = Join-Path $Root 'manifest.json'
$Manifest = [System.IO.File]::ReadAllText($ManifestPath, [System.Text.Encoding]::UTF8) | ConvertFrom-Json
$entryRelative = $Manifest.entryPath -replace '/', '\\'
$JournalName = '.wxnodus-journal.json'
if ($Uninstall) {
  $JournalPath = Join-Path $TargetDir $JournalName
  if (-not (Test-Path $JournalPath)) {
    Write-Error "INSTALLER_UNINSTALL_NO_JOURNAL: $TargetDir"
    exit 1
  }
  $Owned = [System.IO.File]::ReadAllText($JournalPath, [System.Text.Encoding]::UTF8) | ConvertFrom-Json
  foreach ($file in $Owned.files) {
    $p = Join-Path $TargetDir ($file -replace '/', '\\')
    if (Test-Path $p) { Remove-Item $p -Force -ErrorAction SilentlyContinue }
  }
  Remove-Item $JournalPath -Force -ErrorAction SilentlyContinue
  foreach ($dir in $Owned.dirs) {
    $d = Join-Path $TargetDir ($dir -replace '/', '\\')
    if ((Test-Path $d) -and -not (Get-ChildItem $d -Force)) { Remove-Item $d -Force -ErrorAction SilentlyContinue }
  }
  Write-Output "UNINSTALLED: $TargetDir"
  exit 0
}
foreach ($file in $Manifest.files) {
  $actual = (Get-FileHash (Join-Path $Root ($file.path -replace '/', '\\')) -Algorithm SHA256).Hash.ToLowerInvariant()
  if ($actual -ne $file.sha256) {
    Write-Error "INSTALLER_SHA256_MISMATCH: $($file.path) expected $($file.sha256) got $actual"
    exit 1
  }
}
$actualEntry = (Get-FileHash (Join-Path $Root $entryRelative) -Algorithm SHA256).Hash.ToLowerInvariant()
if ($actualEntry -ne $Manifest.entrySha256) {
  Write-Error "INSTALLER_ENTRY_SHA256_MISMATCH: $($Manifest.entryPath)"
  exit 1
}
if ($DryRun) { Write-Output "DRY-RUN OK: $TargetDir"; exit 0 }
$Parent = Split-Path -Parent $TargetDir
New-Item -ItemType Directory -Force -Path $Parent | Out-Null
$Staging = Join-Path $Parent ('.wxnodus-staging-' + [System.IO.Path]::GetRandomFileName())
New-Item -ItemType Directory -Force -Path $Staging | Out-Null
Get-ChildItem -Path $Root -Force | Where-Object { $_.Name -ne 'install.ps1' } | Copy-Item -Recurse -Force -Destination $Staging
Set-Content -Path (Join-Path $Staging 'start.cmd') -Encoding ASCII -Value "@echo off\`r\`nnode \`"%~dp0$entryRelative\`" %*"
if (-not (Test-Path (Join-Path $Staging $entryRelative))) {
  Write-Error "INSTALLER_POSTCONDITION_FAILED: $entryRelative"
  Remove-Item $Staging -Recurse -Force -ErrorAction SilentlyContinue
  exit 1
}
$OwnedFiles = @()
$OwnedDirs = @()
Get-ChildItem -Path $Staging -Recurse | ForEach-Object {
  $rel = $_.FullName.Substring($Staging.Length + 1) -replace '\\\\', '/'
  if ($_.PSIsContainer) { $OwnedDirs += $rel } else { $OwnedFiles += $rel }
}
$JournalContent = @{ files = $OwnedFiles; dirs = $OwnedDirs } | ConvertTo-Json
if (Test-Path $TargetDir) {
  $Backup = Join-Path $Parent ('.wxnodus-backup-' + [System.IO.Path]::GetRandomFileName())
  Rename-Item $TargetDir $Backup
  try {
    Rename-Item $Staging $TargetDir
    Remove-Item $Backup -Recurse -Force
  } catch {
    if (-not (Test-Path $TargetDir)) { Rename-Item $Backup $TargetDir }
    Remove-Item $Staging -Recurse -Force -ErrorAction SilentlyContinue
    Write-Error "INSTALLER_SWITCH_FAILED: rolled back to backup"
    exit 1
  }
} else {
  Rename-Item $Staging $TargetDir
}
Set-Content -Path (Join-Path $TargetDir $JournalName) -Encoding UTF8 -Value $JournalContent
Write-Output "INSTALLED: $TargetDir"
`;
  return Buffer.concat([Buffer.from([0xef, 0xbb, 0xbf]), Buffer.from(body, 'utf8')]);
};

export async function buildInstallerPackage(input: InstallerPackageInput): Promise<OperationResult<InstallerPackageResult>> {
  const name = sanitizeAppName(input.appName);
  if (!name.ok) return name;
  if (!SEMVER.test(input.version)) {
    return { ok: false, error: configError('INSTALLER_VERSION_INVALID', 'installer.version.invalid', { version: input.version }) };
  }
  // P0-03：候选树必须先通过路径策略（../ 逃逸、绝对路径、保留名、重复/大小写冲突、entry 闭包）
  const paths = validateInstallerPaths(input.files.keys(), input.entryPath);
  if (!paths.ok) return paths;
  if (!input.files.has(input.entryPath)) {
    return { ok: false, error: configError('INSTALLER_ENTRY_INVALID', 'installer.entry.invalid', { entryPath: input.entryPath }) };
  }
  const fileList = [...input.files.entries()].map(([path, bytes]) => ({ path, sha256: sha256(bytes), bytes: bytes.length }))
    .sort((a, b) => a.path.localeCompare(b.path));
  const manifest: InstallerPackageManifest = {
    schemaVersion: 2,
    appName: name.value,
    version: input.version,
    icon: input.icon,
    entryPath: input.entryPath,
    entrySha256: sha256(input.files.get(input.entryPath)!),
    files: fileList,
  };
  const manifestBytes = Buffer.from(`${JSON.stringify(manifest, null, 2)}\n`, 'utf8');
  const installerBytes = installScript(manifest);
  const entries: ZipEntryInput[] = [
    { path: 'manifest.json', content: manifestBytes },
    { path: 'install.ps1', content: installerBytes },
    ...fileList.map(file => ({ path: file.path, content: input.files.get(file.path)! })),
  ];
  const zip = buildZip(entries);
  const zipName = `${name.value}-${input.version}.zip`;
  const zipPath = join(input.outDir, zipName);
  try {
    await mkdir(input.outDir, { recursive: true });
    await writeFile(zipPath, zip);
  } catch (cause) {
    return { ok: false, error: configError('INSTALLER_PACKAGE_WRITE_FAILED', 'installer.package.write.failed', { cause: String(cause) }) };
  }
  // 自校验：读回 zip 必须逐字节还原（打包器绝不自欺）
  const readBack = readZip(zip);
  if (!readBack.ok || readBack.value.size !== entries.length) {
    return { ok: false, error: configError('INSTALLER_PACKAGE_READBACK_FAILED', 'installer.package.readback.failed') };
  }
  for (const entry of entries) {
    const stored = readBack.value.get(entry.path);
    if (!stored || !stored.equals(entry.content)) {
      return { ok: false, error: configError('INSTALLER_PACKAGE_READBACK_FAILED', 'installer.package.readback.failed', { path: entry.path }) };
    }
  }
  return {
    ok: true,
    value: {
      zipPath,
      zipSha256: zipSha256(zip),
      manifestSha256: sha256(manifestBytes),
      entryCount: fileList.length,
      manifest,
    },
  };
}
