// src/application/release/installerPackager.ts — 完整安装器打包器（§10-4 完整集成）：
// 文件树 → manifest（全量 sha256 绑定）→ 生成 install.ps1（安装前全量校验，漂移即拒）→ 自研 zip 打包（确定性）
// 产物：<appName>-<version>.zip（manifest.json + install.ps1 + 业务文件）——单文件可分发、可校验、可安装
import { createHash } from 'node:crypto';
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { OperationResult } from '../../protocol/results.js';
import { configError } from '../../domain/config/configSchema.js';
import { sanitizeAppName } from './installerManifest.js';
import { buildZip, readZip, zipSha256, type ZipEntryInput } from './zipArchive.js';
import { psSingleQuotedLiteral } from './powershellLiteral.js';
import { validateInstallerPaths } from './installerPathPolicy.js';

export interface InstallerPackageInput {
  appName: string;
  version: string;
  icon: string | null;
  entryPath: string;
  /** 相对路径 → 内容（含入口文件） */
  files: Map<string, Buffer>;
  outDir: string;
}

export interface InstallerPackageResult {
  zipPath: string;
  zipSha256: string;
  manifestSha256: string;
  entryCount: number;
  manifest: InstallerPackageManifest;
}

export interface InstallerPackageManifest {
  schemaVersion: 2;
  appName: string;
  version: string;
  icon: string | null;
  entryPath: string;
  entrySha256: string;
  files: Array<{ path: string; sha256: string; bytes: number }>;
  /** V4 P3-5：打包机 Node ABI（process.versions.modules）——install.ps1 预检比对 */
  buildAbi?: number;
}

const SEMVER = /^\d+\.\d+\.\d+$/;

const sha256 = (bytes: Buffer) => createHash('sha256').update(bytes).digest('hex');

/** install.ps1 模板（纯 ASCII——PS 5.1 无 BOM 时按 ANSI 解析，非 ASCII 注释会损坏解析；写入时加 UTF-8 BOM 双保险）：
 * 安装前对 manifest 全量哈希校验——任何漂移 → INSTALLER_SHA256_MISMATCH / exit 1。
 * P0-03：appName 经 psSingleQuotedLiteral 编码为被动字面量，绝不裸插入 PowerShell 源码。
 * 2026-08-18 CI 实测：GitHub windows-latest 上从 pwsh 继承环境 spawn 的 powershell.exe(5.1)
 * 解析不到 Get-FileHash（CommandNotFoundException，其余 cmdlet 正常）——哈希改纯 .NET
 * SHA256（Get-WxSha256），零模块依赖，任意用户机器同语义。 */
const installScript = (manifest: InstallerPackageManifest): Buffer => {
  const appNameLiteral = psSingleQuotedLiteral(manifest.appName);
  const body = `# wxnodus installer (generated by installerPackager - deterministic install script)
# Verifies every manifest file sha256 before installing; any drift -> exit 1
# DX-04 lifecycle: staging -> postcondition -> atomic switch (backup/rollback recover)
# -> ownership journal (.wxnodus-journal.json); -Uninstall deletes journaled files only.
param(
  [string]$TargetDir = (Join-Path "$env:LOCALAPPDATA\\Programs" ${appNameLiteral}),
  [switch]$DryRun,
  [switch]$Uninstall,
  [switch]$SkipPath,
  [string]$Source = ''
)
$ErrorActionPreference = 'Stop'
$NodeOk = $false
try {
  $NodeVer = & node -v 2>$null
  if ($NodeVer -match '^v(\\d+)\\.') {
    $major = [int]$Matches[1]
    # V4 P3-5: hard gate Node >= 22.7 (ESM detect-module semantics + engines contract;
    # installer ships ESM-only dist without transpile - older Node fails at startup, not install)
    if ($major -gt 22 -or ($major -eq 22 -and (([version]$NodeVer.Substring(1)).Minor -ge 7))) {
      $NodeOk = $true
    } elseif ($major -ge 22) {
      Write-Output "FAIL: Node $NodeVer is 22.x but below 22.7 - ESM startup requires >= 22.7"
    }
  }
} catch { }
if (-not $NodeOk) {
  Write-Error "INSTALLER_NODE_MISSING: Node.js 18+ required (22 recommended). Install: https://nodejs.org/ (CN mirror: https://npmmirror.com/mirrors/node/) then re-run this script."
  exit 1
}
# Pure .NET sha256: Get-FileHash is not resolvable on some hosts (verified: GitHub
# windows-latest Windows PowerShell 5.1 spawned from pwsh-inherited env -> CommandNotFound).
function Get-WxSha256([string]$Path) {
  $sha = [System.Security.Cryptography.SHA256]::Create()
  $stream = [System.IO.File]::OpenRead($Path)
  try {
    return ([System.BitConverter]::ToString($sha.ComputeHash($stream)) -replace '-', '').ToLowerInvariant()
  } finally {
    $stream.Dispose()
  }
}
$Root = Split-Path -Parent $MyInvocation.MyCommand.Path
$ManifestPath = Join-Path $Root 'manifest.json'
# V4 P3-5: read builder ABI from manifest (single field read - full manifest validated later)
$Manifest = [System.IO.File]::ReadAllText($ManifestPath, [System.Text.Encoding]::UTF8) | ConvertFrom-Json
$ManifestAbi = $Manifest.buildAbi
# V4 P3-5: ABI check (after Node gate) - native modules compiled for builder ABI;
# mismatch means NODE_MODULE_VERSION crash at require time
$LocalAbi = (& node -p "process.versions.modules" 2>$null)
if ($NodeOk -and $LocalAbi -and $ManifestAbi -and [int]$LocalAbi -ne [int]$ManifestAbi) {
  Write-Output "FAIL: Node ABI mismatch (local $LocalAbi vs built $ManifestAbi) - native modules require the builder Node line"
  $NodeOk = $false
}
$entryRelative = $Manifest.entryPath -replace '/', '\\'
$JournalName = '.wxnodus-journal.json'
if ($Uninstall) {
  $JournalPath = Join-Path $TargetDir $JournalName
  if (-not (Test-Path $JournalPath)) {
    Write-Error "INSTALLER_UNINSTALL_NO_JOURNAL: $TargetDir"
    exit 1
  }
  $Owned = [System.IO.File]::ReadAllText($JournalPath, [System.Text.Encoding]::UTF8) | ConvertFrom-Json
  foreach ($file in $Owned.files) {
    $p = Join-Path $TargetDir ($file -replace '/', '\\')
    if (Test-Path $p) { Remove-Item $p -Force -ErrorAction SilentlyContinue }
  }
  Remove-Item $JournalPath -Force -ErrorAction SilentlyContinue
  foreach ($dir in $Owned.dirs) {
    $d = Join-Path $TargetDir ($dir -replace '/', '\\')
    if ((Test-Path $d) -and -not (Get-ChildItem $d -Force)) { Remove-Item $d -Force -ErrorAction SilentlyContinue }
  }
  Write-Output "UNINSTALLED: $TargetDir"
  exit 0
}
foreach ($file in $Manifest.files) {
  $actual = Get-WxSha256 (Join-Path $Root ($file.path -replace '/', '\\'))
  if ($actual -ne $file.sha256) {
    Write-Error "INSTALLER_SHA256_MISMATCH: $($file.path) expected $($file.sha256) got $actual"
    exit 1
  }
}
$actualEntry = Get-WxSha256 (Join-Path $Root $entryRelative)
if ($actualEntry -ne $Manifest.entrySha256) {
  Write-Error "INSTALLER_ENTRY_SHA256_MISMATCH: $($Manifest.entryPath)"
  exit 1
}
if ($DryRun) { Write-Output "DRY-RUN OK: $TargetDir"; exit 0 }
$OldVersion = ''
$OldMetaPath = Join-Path $TargetDir 'install-meta.json'
if (Test-Path $OldMetaPath) {
  try {
    $OldMeta = [System.IO.File]::ReadAllText($OldMetaPath, [System.Text.Encoding]::UTF8) | ConvertFrom-Json
    $OldVersion = [string]$OldMeta.version
  } catch { }
}
$Parent = Split-Path -Parent $TargetDir
New-Item -ItemType Directory -Force -Path $Parent | Out-Null
$Staging = Join-Path $Parent ('.wxnodus-staging-' + [System.IO.Path]::GetRandomFileName())
New-Item -ItemType Directory -Force -Path $Staging | Out-Null
# robocopy：字面路径 + 长路径（>260）安全（Copy-Item 在深路径下失败）；/XF 排除安装器工具本身（不属安装物）
& robocopy $Root $Staging /E /NFL /NDL /NJH /NJS /NP /XF install.ps1 install.bat | Out-Null
if ($LASTEXITCODE -ge 8) {
  Remove-Item $Staging -Recurse -Force -ErrorAction SilentlyContinue
  Write-Error "INSTALLER_STAGING_FAILED: robocopy exit $LASTEXITCODE"
  exit 1
}
Set-Content -Path (Join-Path $Staging (${appNameLiteral} + '.cmd')) -Encoding ASCII -Value "@echo off\`r\`nset \`"WXNODUS_DATA_DIR=%LOCALAPPDATA%\\wxnodus\`"\`r\`nnode \`"%~dp0$entryRelative\`" %*"
# wxn 别名（npm bin 双命令契约对齐——winget/scoop manifest 均声明 wxn，安装器必须真实产出）
Set-Content -Path (Join-Path $Staging 'wxn.cmd') -Encoding ASCII -Value "@echo off\`r\`nset \`"WXNODUS_DATA_DIR=%LOCALAPPDATA%\\wxnodus\`"\`r\`nnode \`"%~dp0$entryRelative\`" %*"
if (-not (Test-Path (Join-Path $Staging $entryRelative))) {
  Write-Error "INSTALLER_POSTCONDITION_FAILED: $entryRelative"
  Remove-Item $Staging -Recurse -Force -ErrorAction SilentlyContinue
  exit 1
}
# journal 由 manifest 确定性推导（绝不递归深路径）：manifest 全量文件 + <appName>.cmd + manifest.json + install-meta.json；
# 目录 = 文件祖先集，长度降序（先删子目录再删父目录，只删空目录）
$OwnedFiles = @($Manifest.files | ForEach-Object { $_.path }) + @((${appNameLiteral} + '.cmd'), 'wxn.cmd', 'manifest.json', 'install-meta.json')
$DirSet = @{}
foreach ($f in $OwnedFiles) {
  $parts = ($f -replace '/', '\\').Split('\\')
  for ($i = 0; $i -lt ($parts.Count - 1); $i++) {
    $d = ($parts[0..$i] -join '\\')
    if ($d) { $DirSet[$d] = $true }
  }
}
$OwnedDirs = @($DirSet.Keys | Sort-Object { $_.Length } -Descending)
$JournalContent = @{ files = $OwnedFiles; dirs = $OwnedDirs } | ConvertTo-Json
if (Test-Path $TargetDir) {
  $Backup = Join-Path $Parent ('.wxnodus-backup-' + [System.IO.Path]::GetRandomFileName())
  Rename-Item $TargetDir $Backup
  try {
    Rename-Item $Staging $TargetDir
    Remove-Item $Backup -Recurse -Force
  } catch {
    if (-not (Test-Path $TargetDir)) { Rename-Item $Backup $TargetDir }
    Remove-Item $Staging -Recurse -Force -ErrorAction SilentlyContinue
    Write-Error "INSTALLER_SWITCH_FAILED: rolled back to backup"
    exit 1
  }
} else {
  Rename-Item $Staging $TargetDir
}
Set-Content -Path (Join-Path $TargetDir $JournalName) -Encoding UTF8 -Value $JournalContent
$Meta = @{ app = $Manifest.appName; version = $Manifest.version; installedAt = (Get-Date -Format 'o') }
if ($Source) { $Meta['source'] = $Source }
# 无 BOM UTF-8（PS 5.1 Set-Content -Encoding UTF8 带 BOM，JSON.parse 会炸——.NET 显式关闭标识符）
[System.IO.File]::WriteAllText((Join-Path $TargetDir 'install-meta.json'), ($Meta | ConvertTo-Json), (New-Object System.Text.UTF8Encoding($false)))
if ($OldVersion -and $OldVersion -eq $Manifest.version) {
  Write-Output "REINSTALL_SAME_VERSION: $($Manifest.version) (reinstalled over same version - data at %LOCALAPPDATA%\\wxnodus untouched)"
}
if (-not $SkipPath) {
  try {
    $userPath = [Environment]::GetEnvironmentVariable('Path', 'User')
    if ($userPath -and (($userPath -split ';') -contains $TargetDir)) {
      Write-Output "PATH_ALREADY_PRESENT: $TargetDir"
    } else {
      $newPath = if ($userPath) { $userPath.TrimEnd(';') + ';' + $TargetDir } else { $TargetDir }
      [Environment]::SetEnvironmentVariable('Path', $newPath, 'User')
      Write-Output "PATH_UPDATED: $TargetDir"
    }
  } catch {
    Write-Output "WARN: PATH registration failed (add manually): $TargetDir"
  }
}
Write-Output "INSTALLED: $TargetDir"
`;
  return Buffer.concat([Buffer.from([0xef, 0xbb, 0xbf]), Buffer.from(body, 'utf8')]);
};

/** install.bat 双击向导（静态、纯 ASCII）：零命令行安装入口——解压后双击即装（Node 预检 + 调 install.ps1）。 */
const installBat = Buffer.from(
  '@echo off\r\n' +
  'rem wxnodus one-click installer (double-click, no command line needed)\r\n' +
  'setlocal\r\n' +
  'set "DIR=%~dp0"\r\n' +
  'where node >nul 2>nul\r\n' +
  'if errorlevel 1 (\r\n' +
  '  echo [x] Node.js not found. Install Node 18+ (recommended 22):\r\n' +
  '  echo     https://nodejs.org/  (CN mirror: https://npmmirror.com/mirrors/node/)\r\n' +
  '  pause\r\n' +
  '  exit /b 1\r\n' +
  ')\r\n' +
  'powershell -NoProfile -ExecutionPolicy Bypass -File "%DIR%install.ps1"\r\n' +
  'if errorlevel 1 (\r\n' +
  '  echo [!] Install failed - see messages above.\r\n' +
  '  pause\r\n' +
  '  exit /b 1\r\n' +
  ')\r\n' +
  'echo.\r\n' +
  'echo [OK] Installed. Open a NEW cmd window and run: wxnodus\r\n' +
  'pause\r\n',
  'utf8',
);

export async function buildInstallerPackage(input: InstallerPackageInput): Promise<OperationResult<InstallerPackageResult>> {
  const name = sanitizeAppName(input.appName);
  if (!name.ok) return name;
  if (!SEMVER.test(input.version)) {
    return { ok: false, error: configError('INSTALLER_VERSION_INVALID', 'installer.version.invalid', { version: input.version }) };
  }
  // P0-03：候选树必须先通过路径策略（../ 逃逸、绝对路径、保留名、重复/大小写冲突、entry 闭包）
  const paths = validateInstallerPaths(input.files.keys(), input.entryPath);
  if (!paths.ok) return paths;
  if (!input.files.has(input.entryPath)) {
    return { ok: false, error: configError('INSTALLER_ENTRY_INVALID', 'installer.entry.invalid', { entryPath: input.entryPath }) };
  }
  const fileList = [...input.files.entries()].map(([path, bytes]) => ({ path, sha256: sha256(bytes), bytes: bytes.length }))
    .sort((a, b) => a.path.localeCompare(b.path));
  // V4 P3-5：manifest 记录打包机 ABI（原生模块 better-sqlite3/robotjs 按此编译——
  // install.ps1 预检比对，不匹配即 NODE_MODULE_VERSION 崩）
  const buildAbi = Number(process.versions.modules);
  const manifest: InstallerPackageManifest = {
    schemaVersion: 2,
    appName: name.value,
    version: input.version,
    icon: input.icon,
    entryPath: input.entryPath,
    entrySha256: sha256(input.files.get(input.entryPath)!),
    files: fileList,
    buildAbi, // V4 P3-5：打包机 Node ABI（install.ps1 预检比对——原生模块版本一致性）
  };
  const manifestBytes = Buffer.from(`${JSON.stringify(manifest, null, 2)}\n`, 'utf8');
  const installerBytes = installScript(manifest);
  const entries: ZipEntryInput[] = [
    { path: 'manifest.json', content: manifestBytes },
    { path: 'install.ps1', content: installerBytes },
    { path: 'install.bat', content: installBat },
    ...fileList.map(file => ({ path: file.path, content: input.files.get(file.path)! })),
  ];
  const zip = buildZip(entries);
  const zipName = `${name.value}-${input.version}.zip`;
  const zipPath = join(input.outDir, zipName);
  try {
    await mkdir(input.outDir, { recursive: true });
    await writeFile(zipPath, zip);
  } catch (cause) {
    return { ok: false, error: configError('INSTALLER_PACKAGE_WRITE_FAILED', 'installer.package.write.failed', { cause: String(cause) }) };
  }
  // 自校验：读回 zip 必须逐字节还原（打包器绝不自欺）
  const readBack = readZip(zip);
  if (!readBack.ok || readBack.value.size !== entries.length) {
    return { ok: false, error: configError('INSTALLER_PACKAGE_READBACK_FAILED', 'installer.package.readback.failed') };
  }
  for (const entry of entries) {
    const stored = readBack.value.get(entry.path);
    if (!stored || !stored.equals(entry.content)) {
      return { ok: false, error: configError('INSTALLER_PACKAGE_READBACK_FAILED', 'installer.package.readback.failed', { path: entry.path }) };
    }
  }
  return {
    ok: true,
    value: {
      zipPath,
      zipSha256: zipSha256(zip),
      manifestSha256: sha256(manifestBytes),
      entryCount: fileList.length,
      manifest,
    },
  };
}
